### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by sgandro** [leoru/SwiftLoader#17]
by turning the device is not drawn again

**Comment by lokesh213** [comment]
how to set frame for landscape.

**Comment by qburst-vineeth** [comment]
You can resolve the issue by adding the following code in **_SwiftLoader.swift_**

> ```
> override public func layoutSubviews() {
> 
>     super.layoutSubviews()
> 
>     let loader = SwiftLoader.sharedInstance
> 
>     let height : CGFloat = UIScreen.mainScreen().bounds.size.height
>     let width : CGFloat = UIScreen.mainScreen().bounds.size.width
>     let center : CGPoint = CGPoint(x: width / 2.0, y: height / 2.0)
> 
>     loader.center = center
>     loader.coverView?.frame = UIScreen.mainScreen().bounds
> }
> ```
