### ISSUE TITLE
Convert to Swift 3

### ISSUE THREAD

**Issue by kevinmanncito** [leoru/SwiftLoader#24]
Need a version that works with swift 3

**Comment by kevinmanncito** [comment]
Testing with this fork: https://github.com/kevinmanncito/SwiftLoader/tree/swift3

**Comment by caraballoj** [comment]
yes I'm having the same issues. I just updated to Xcode 8.0 and SwiftLoader is not compatible.

**Comment by SimranpreetChahal** [comment]
SwiftLoader is not compatible with sift3.Please provide an updated pod.
