### ISSUE TITLE
Getting crashes for iOS version greater than 15. Not getting any logs/clue. Could you please help.

### ISSUE THREAD

**Issue by shivanand217** [leoru/SwiftLoader#32]
![Screenshot 2022-02-18 at 12 04 26 PM](https://user-images.githubusercontent.com/17709435/154630519-bfcb97a2-cc91-4e0d-a1e0-ee5bebbb2751.png)

@leoru @jonpacker @mikekavouras @maykonmeier @PhilippeRiegert

**Comment by shivanand217** [comment]
I think we have fixed this issue, but still need to test out the changes. In the static function class func show() the UIApplication's keywindow is forcefully unwrapped, and as per the documentation, keywindow is deprecated for iOS version > 13. So that must be causing the crash.

**Comment by leoru** [comment]
Hi @shivanand217, thanks for the issue report, I made an update that adopt the loader code for iOS 13 and later. 
`UIApplication's keywindow` is also fixed now.
