### ISSUE TITLE
'SwiftLoader.Config' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by 10printhello** [leoru/SwiftLoader#4]
I'm using xcode 6.3. Any ideas?

var config : SwiftLoader.Config = SwiftLoader.Config()     <- Issue against this line
config.size = 150
config.spinnerColor = UIColor.redColor()
SwiftLoader.setConfig(config)

**Comment by leoru** [comment]
Hi!
My bad, i lost public modifier in vars in Config. I updated this in 0.2.1 version.

**Comment by 10printhello** [comment]
Updated my pod file to 0.2.1 and ran install. Still get the same error message.

**Comment by leoru** [comment]
Fixed now in 0.2.2

**Comment by 10printhello** [comment]
Works like a charm. Thanks for fixing it so quickly!

**Comment by leoru** [comment]
You are welcome!
