### ISSUE TITLE
SwiftLoader.show is crashed

### ISSUE THREAD

**Issue by svyatoslav-reshetnikov** [leoru/SwiftLoader#6]
Hello!

I try to used this library. About 2 month ago it work perfect. When i try to use SwiftLoader in my other project, app fails with "fatal error: unexpectedly found nil while unwrapping an Optional value". I see XCode log - this error in your function "show".

About code. I just copy code from your example and paste it in my program.

**Comment by leoru** [comment]
Hi! 
I'try to check it tomorrow and fix it.

**Comment by leoru** [comment]
Fixed in v0.2.5
