### ISSUE TITLE
Crashes when calling hide() without first calling show()

### ISSUE THREAD

**Issue by muuhoffman** [leoru/SwiftLoader#7]
I know this may not necessarily be a bug, but it would be a nice problem to solve.  

Scenario: I want to show the loader, and have stuff happen in the background, then use a notification to alert the view when finished, and in that notification handler, I will hide the loader.  However, I also, want to use that notification to be called when the view initialize the process, so the notification would be called but the loader never would have been shown.

Question/Issue: Is there a property or something I can check to conditionally hide the loader, only if it has been shown first.  Or better yet, I would love to just be able to call hide without checking, and it hides the loader if it was shown, or does nothing if it never was shown.

**Comment by leoru** [comment]
I fix it in v0.2.5
